# run: conda env create --file dpn-gpu-environment.yml
name: dpn-gpu-env
dependencies:
- python==3.6
- anaconda
- pip
- numpy
- scipy
- Pillow
- cython
- matplotlib
- scikit-image
- h5py
- IPython[all]
- tensorflow-gpu==1.13.1
- pip:
  - imgaug
  - keras==2.1.3
  - opencv-python==3.3.0.9
