# run: conda env create --file dpn-cpu-environment.yml
name: dpn-cpu-env
dependencies:
- python>=3.4
- anaconda
- pip
- numpy
- scipy
- Pillow
- cython
- matplotlib
- scikit-image
- h5py
- IPython[all]
- tensorflow==1.13.1
- pip:
  - imgaug
  - keras==2.1.3
  - opencv-python==3.3.0.9
